apiVersion: v1
kind: Service
metadata:
  name: bitunnel-cron
  labels:
    app: bitunnel-cron
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bitunnel-cron