apiVersion: v1
kind: ReplicationController
metadata:
  name: bitunnel-cron-1
spec:
  replicas: 1
  selector:
    app: bitunnel-cron
    buildVersion: "build-1"
  template:
    metadata:
      labels:
        app: bitunnel-cron
        buildVersion: "build-1"
    spec:
      containers:
      - name: bitunnel-cron
        image: docker.io/tradedepot/bitunnel-cron:latest
        ports:
        - containerPort: 80
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: REDIS_MASTER
          value: "bitunnel-r-prod.znw8ii.ng.0001.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        - name: ES_URL  
          value: "search-bitunnel-pro-dipt3f2wqmurrsc6z6twdr5nlm.us-east-1.es.amazonaws.com:80"
        - name: MAIL_URL  
          value: "smtps://bitunnel%40c2gconsulting.com:1ndieg0g0@smtp.gmail.com"
